# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Fundamentos de Programación
author:  Álvaro Mauricio Montenegro Díaz, Daniel Mauricio Montenegro Reyes
logo: logo-final-ap.png
copyright: '2022'
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/AprendizajeProfundo/Libro_Fundamentos_Programacion  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
sphinx:
  extra_extensions:
  - sphinx_inline_tabs
  - sphinx_click.ext
  comments:
    hypothesis              : true
    utterances:
      repo: #Repository
  config:
    bibtex_reference_style: author_year
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

# Information about where the book exists on the web
launch_buttons:
  notebook_interface: classic
  thebe: true  
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com
